// Code generated by protoc-gen-go. DO NOT EDIT.
// source: speed-control.proto

package protocol

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Record struct {
	Date                 int64    `protobuf:"varint,1,opt,name=date,proto3" json:"date,omitempty"`
	Number               string   `protobuf:"bytes,2,opt,name=number,proto3" json:"number,omitempty"`
	Speed                float32  `protobuf:"fixed32,3,opt,name=speed,proto3" json:"speed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Record) Reset()         { *m = Record{} }
func (m *Record) String() string { return proto.CompactTextString(m) }
func (*Record) ProtoMessage()    {}
func (*Record) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3ed8d88f284cfe2, []int{0}
}

func (m *Record) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Record.Unmarshal(m, b)
}
func (m *Record) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Record.Marshal(b, m, deterministic)
}
func (m *Record) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Record.Merge(m, src)
}
func (m *Record) XXX_Size() int {
	return xxx_messageInfo_Record.Size(m)
}
func (m *Record) XXX_DiscardUnknown() {
	xxx_messageInfo_Record.DiscardUnknown(m)
}

var xxx_messageInfo_Record proto.InternalMessageInfo

func (m *Record) GetDate() int64 {
	if m != nil {
		return m.Date
	}
	return 0
}

func (m *Record) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *Record) GetSpeed() float32 {
	if m != nil {
		return m.Speed
	}
	return 0
}

type AddRequest struct {
	Record               *Record  `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddRequest) Reset()         { *m = AddRequest{} }
func (m *AddRequest) String() string { return proto.CompactTextString(m) }
func (*AddRequest) ProtoMessage()    {}
func (*AddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3ed8d88f284cfe2, []int{1}
}

func (m *AddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRequest.Unmarshal(m, b)
}
func (m *AddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRequest.Marshal(b, m, deterministic)
}
func (m *AddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRequest.Merge(m, src)
}
func (m *AddRequest) XXX_Size() int {
	return xxx_messageInfo_AddRequest.Size(m)
}
func (m *AddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddRequest proto.InternalMessageInfo

func (m *AddRequest) GetRecord() *Record {
	if m != nil {
		return m.Record
	}
	return nil
}

type EmptyResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyResponse) Reset()         { *m = EmptyResponse{} }
func (m *EmptyResponse) String() string { return proto.CompactTextString(m) }
func (*EmptyResponse) ProtoMessage()    {}
func (*EmptyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3ed8d88f284cfe2, []int{2}
}

func (m *EmptyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyResponse.Unmarshal(m, b)
}
func (m *EmptyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyResponse.Marshal(b, m, deterministic)
}
func (m *EmptyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyResponse.Merge(m, src)
}
func (m *EmptyResponse) XXX_Size() int {
	return xxx_messageInfo_EmptyResponse.Size(m)
}
func (m *EmptyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyResponse proto.InternalMessageInfo

type ListingRequest struct {
	Date                 int64    `protobuf:"varint,1,opt,name=date,proto3" json:"date,omitempty"`
	SpeedLimit           float32  `protobuf:"fixed32,2,opt,name=speedLimit,proto3" json:"speedLimit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListingRequest) Reset()         { *m = ListingRequest{} }
func (m *ListingRequest) String() string { return proto.CompactTextString(m) }
func (*ListingRequest) ProtoMessage()    {}
func (*ListingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3ed8d88f284cfe2, []int{3}
}

func (m *ListingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListingRequest.Unmarshal(m, b)
}
func (m *ListingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListingRequest.Marshal(b, m, deterministic)
}
func (m *ListingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListingRequest.Merge(m, src)
}
func (m *ListingRequest) XXX_Size() int {
	return xxx_messageInfo_ListingRequest.Size(m)
}
func (m *ListingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListingRequest proto.InternalMessageInfo

func (m *ListingRequest) GetDate() int64 {
	if m != nil {
		return m.Date
	}
	return 0
}

func (m *ListingRequest) GetSpeedLimit() float32 {
	if m != nil {
		return m.SpeedLimit
	}
	return 0
}

type ListingResponse struct {
	Record               []*Record `protobuf:"bytes,1,rep,name=record,proto3" json:"record,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ListingResponse) Reset()         { *m = ListingResponse{} }
func (m *ListingResponse) String() string { return proto.CompactTextString(m) }
func (*ListingResponse) ProtoMessage()    {}
func (*ListingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3ed8d88f284cfe2, []int{4}
}

func (m *ListingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListingResponse.Unmarshal(m, b)
}
func (m *ListingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListingResponse.Marshal(b, m, deterministic)
}
func (m *ListingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListingResponse.Merge(m, src)
}
func (m *ListingResponse) XXX_Size() int {
	return xxx_messageInfo_ListingResponse.Size(m)
}
func (m *ListingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListingResponse proto.InternalMessageInfo

func (m *ListingResponse) GetRecord() []*Record {
	if m != nil {
		return m.Record
	}
	return nil
}

type GetMinMaxResponse struct {
	Min                  *Record  `protobuf:"bytes,1,opt,name=min,proto3" json:"min,omitempty"`
	Max                  *Record  `protobuf:"bytes,2,opt,name=max,proto3" json:"max,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMinMaxResponse) Reset()         { *m = GetMinMaxResponse{} }
func (m *GetMinMaxResponse) String() string { return proto.CompactTextString(m) }
func (*GetMinMaxResponse) ProtoMessage()    {}
func (*GetMinMaxResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3ed8d88f284cfe2, []int{5}
}

func (m *GetMinMaxResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMinMaxResponse.Unmarshal(m, b)
}
func (m *GetMinMaxResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMinMaxResponse.Marshal(b, m, deterministic)
}
func (m *GetMinMaxResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMinMaxResponse.Merge(m, src)
}
func (m *GetMinMaxResponse) XXX_Size() int {
	return xxx_messageInfo_GetMinMaxResponse.Size(m)
}
func (m *GetMinMaxResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMinMaxResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMinMaxResponse proto.InternalMessageInfo

func (m *GetMinMaxResponse) GetMin() *Record {
	if m != nil {
		return m.Min
	}
	return nil
}

func (m *GetMinMaxResponse) GetMax() *Record {
	if m != nil {
		return m.Max
	}
	return nil
}

type GetMinMaxRequest struct {
	Date                 int64    `protobuf:"varint,1,opt,name=date,proto3" json:"date,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMinMaxRequest) Reset()         { *m = GetMinMaxRequest{} }
func (m *GetMinMaxRequest) String() string { return proto.CompactTextString(m) }
func (*GetMinMaxRequest) ProtoMessage()    {}
func (*GetMinMaxRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3ed8d88f284cfe2, []int{6}
}

func (m *GetMinMaxRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMinMaxRequest.Unmarshal(m, b)
}
func (m *GetMinMaxRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMinMaxRequest.Marshal(b, m, deterministic)
}
func (m *GetMinMaxRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMinMaxRequest.Merge(m, src)
}
func (m *GetMinMaxRequest) XXX_Size() int {
	return xxx_messageInfo_GetMinMaxRequest.Size(m)
}
func (m *GetMinMaxRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMinMaxRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMinMaxRequest proto.InternalMessageInfo

func (m *GetMinMaxRequest) GetDate() int64 {
	if m != nil {
		return m.Date
	}
	return 0
}

func init() {
	proto.RegisterType((*Record)(nil), "protocol.Record")
	proto.RegisterType((*AddRequest)(nil), "protocol.AddRequest")
	proto.RegisterType((*EmptyResponse)(nil), "protocol.EmptyResponse")
	proto.RegisterType((*ListingRequest)(nil), "protocol.ListingRequest")
	proto.RegisterType((*ListingResponse)(nil), "protocol.ListingResponse")
	proto.RegisterType((*GetMinMaxResponse)(nil), "protocol.GetMinMaxResponse")
	proto.RegisterType((*GetMinMaxRequest)(nil), "protocol.GetMinMaxRequest")
}

func init() {
	proto.RegisterFile("speed-control.proto", fileDescriptor_b3ed8d88f284cfe2)
}

var fileDescriptor_b3ed8d88f284cfe2 = []byte{
	// 319 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0xc1, 0x4b, 0xc3, 0x30,
	0x14, 0xc6, 0xe9, 0xaa, 0xd5, 0xbd, 0xa1, 0x9b, 0x71, 0x68, 0xad, 0x20, 0x23, 0x07, 0xe9, 0xc5,
	0x1d, 0xa6, 0x78, 0x11, 0x84, 0xc9, 0x44, 0x90, 0xed, 0x12, 0x8f, 0x9e, 0xba, 0xe6, 0x21, 0xc1,
	0x35, 0xa9, 0x69, 0x26, 0xf3, 0x4f, 0xf4, 0xbf, 0x12, 0xd3, 0xae, 0x5d, 0xa5, 0xf3, 0xd4, 0x26,
	0xdf, 0x97, 0xdf, 0xfb, 0xde, 0x07, 0xc7, 0x59, 0x8a, 0xc8, 0xaf, 0x62, 0x25, 0x8d, 0x56, 0x8b,
	0x61, 0xaa, 0x95, 0x51, 0x64, 0xdf, 0x7e, 0x62, 0xb5, 0xa0, 0xcf, 0xe0, 0x31, 0x8c, 0x95, 0xe6,
	0x84, 0xc0, 0x0e, 0x8f, 0x0c, 0xfa, 0xce, 0xc0, 0x09, 0x5d, 0x66, 0xff, 0xc9, 0x09, 0x78, 0x72,
	0x99, 0xcc, 0x51, 0xfb, 0xad, 0x81, 0x13, 0xb6, 0x59, 0x71, 0x22, 0x7d, 0xd8, 0xb5, 0x58, 0xdf,
	0x1d, 0x38, 0x61, 0x8b, 0xe5, 0x07, 0x7a, 0x0b, 0x30, 0xe6, 0x9c, 0xe1, 0xc7, 0x12, 0x33, 0x43,
	0x42, 0xf0, 0xb4, 0x25, 0x5b, 0x62, 0x67, 0xd4, 0x1b, 0xae, 0x87, 0x0e, 0xf3, 0x89, 0xac, 0xd0,
	0x69, 0x17, 0x0e, 0x1e, 0x93, 0xd4, 0x7c, 0x31, 0xcc, 0x52, 0x25, 0x33, 0xa4, 0x13, 0x38, 0x9c,
	0x8a, 0xcc, 0x08, 0xf9, 0xb6, 0x86, 0x35, 0x85, 0xbb, 0x00, 0xb0, 0x73, 0xa7, 0x22, 0x11, 0xc6,
	0x06, 0x6c, 0xb1, 0x8d, 0x1b, 0x7a, 0x07, 0xdd, 0x92, 0x92, 0x83, 0x6b, 0x99, 0xdc, 0x7f, 0x33,
	0xbd, 0xc2, 0xd1, 0x13, 0x9a, 0x99, 0x90, 0xb3, 0x68, 0x55, 0x3e, 0xa7, 0xe0, 0x26, 0x42, 0x6e,
	0xdd, 0xe7, 0x57, 0xb4, 0x9e, 0x68, 0x65, 0xe3, 0x34, 0x7b, 0xa2, 0x15, 0xbd, 0x84, 0xde, 0x06,
	0x7c, 0xeb, 0x86, 0xa3, 0x6f, 0x07, 0x3a, 0x0f, 0x4a, 0xbd, 0xbf, 0xa0, 0xfe, 0x14, 0x31, 0x92,
	0x1b, 0x70, 0xc7, 0x9c, 0x93, 0x7e, 0x45, 0xad, 0xfa, 0x0e, 0x4e, 0xab, 0xdb, 0x5a, 0x9b, 0xe4,
	0x1e, 0xf6, 0x8a, 0x1e, 0x88, 0x5f, 0x79, 0xea, 0x05, 0x07, 0x67, 0x0d, 0x4a, 0xf1, 0x7e, 0x02,
	0xed, 0x32, 0x2d, 0x09, 0x2a, 0xdf, 0xdf, 0x15, 0x82, 0xf3, 0x46, 0x2d, 0xa7, 0xcc, 0x3d, 0xab,
	0x5d, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0xfd, 0xa5, 0x5c, 0xc4, 0x90, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BookServiceClient is the client API for BookService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BookServiceClient interface {
	Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	Listing(ctx context.Context, in *ListingRequest, opts ...grpc.CallOption) (*ListingResponse, error)
	GetMinMax(ctx context.Context, in *GetMinMaxRequest, opts ...grpc.CallOption) (*GetMinMaxResponse, error)
}

type bookServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBookServiceClient(cc grpc.ClientConnInterface) BookServiceClient {
	return &bookServiceClient{cc}
}

func (c *bookServiceClient) Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/protocol.BookService/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookServiceClient) Listing(ctx context.Context, in *ListingRequest, opts ...grpc.CallOption) (*ListingResponse, error) {
	out := new(ListingResponse)
	err := c.cc.Invoke(ctx, "/protocol.BookService/Listing", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookServiceClient) GetMinMax(ctx context.Context, in *GetMinMaxRequest, opts ...grpc.CallOption) (*GetMinMaxResponse, error) {
	out := new(GetMinMaxResponse)
	err := c.cc.Invoke(ctx, "/protocol.BookService/GetMinMax", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BookServiceServer is the server API for BookService service.
type BookServiceServer interface {
	Add(context.Context, *AddRequest) (*EmptyResponse, error)
	Listing(context.Context, *ListingRequest) (*ListingResponse, error)
	GetMinMax(context.Context, *GetMinMaxRequest) (*GetMinMaxResponse, error)
}

// UnimplementedBookServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBookServiceServer struct {
}

func (*UnimplementedBookServiceServer) Add(ctx context.Context, req *AddRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (*UnimplementedBookServiceServer) Listing(ctx context.Context, req *ListingRequest) (*ListingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Listing not implemented")
}
func (*UnimplementedBookServiceServer) GetMinMax(ctx context.Context, req *GetMinMaxRequest) (*GetMinMaxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMinMax not implemented")
}

func RegisterBookServiceServer(s *grpc.Server, srv BookServiceServer) {
	s.RegisterService(&_BookService_serviceDesc, srv)
}

func _BookService_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.BookService/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceServer).Add(ctx, req.(*AddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookService_Listing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceServer).Listing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.BookService/Listing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceServer).Listing(ctx, req.(*ListingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookService_GetMinMax_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMinMaxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceServer).GetMinMax(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.BookService/GetMinMax",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceServer).GetMinMax(ctx, req.(*GetMinMaxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BookService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protocol.BookService",
	HandlerType: (*BookServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _BookService_Add_Handler,
		},
		{
			MethodName: "Listing",
			Handler:    _BookService_Listing_Handler,
		},
		{
			MethodName: "GetMinMax",
			Handler:    _BookService_GetMinMax_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "speed-control.proto",
}
